import Head from "next/head";
import { Inter } from "next/font/google";
import CreatePost from "@/components/CreatePost/CreatePost";
import { useAddress } from "@thirdweb-dev/react";
import Header from "@/components/Header/Header";
import { useQuery } from "@apollo/client";
import EssenceCard from "@/components/EssenceCard/EssenceCard";
import { ESSENCES_BY_FILTER } from "@/graphql/EssencesByFilter";
import {
  Essence,
  EssencesByFilterQuery,
  VerifyEssenceMetadataInput,
} from "@/Types/__generated__/graphql";
import InfiniteScroll from "react-infinite-scroll-component";
import { useEffect, useRef, LegacyRef } from "react";
import { Application } from "@splinetool/runtime";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const address = useAddress();
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const { data, error, loading } = useQuery(ESSENCES_BY_FILTER, {
    variables: {
      me: address,
      appID: "example_1552",
    },
  });

  useEffect(() => {
    if (!canvasRef.current) return;
    const app = new Application(canvasRef.current);
    // app.load("https://prod.spline.design/Rq0qmGbx-sDBpRBL/scene.splinecode");
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-background min-w-full min-h-screen">
        <Header />
        <CreatePost />
        <section className="px-2 py-1 md:px-8 md:py-2  custom-grid">
          {/* <InfiniteScroll ></InfiniteScroll> */}
          {data?.essenceByFilter?.map((item) => {
            return <EssenceCard key={item?.essenceID} data={item as Essence} />;
          })}
        </section>
      </main>
    </>
  );
}
